# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appchecker_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppcheckerWindow(object):
    def setupUi(self, AppcheckerWindow):
        AppcheckerWindow.setObjectName("AppcheckerWindow")
        AppcheckerWindow.resize(706, 439)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        AppcheckerWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/pictures/hacker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AppcheckerWindow.setWindowIcon(icon)
        AppcheckerWindow.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.gridLayout_5 = QtWidgets.QGridLayout(AppcheckerWindow)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_1 = QtWidgets.QGroupBox(AppcheckerWindow)
        self.groupBox_1.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_1.setStyleSheet("")
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_1)
        self.gridLayout.setObjectName("gridLayout")
        self.openButton = QtWidgets.QPushButton(self.groupBox_1)
        self.openButton.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.openButton.setFont(font)
        self.openButton.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.openButton.setCheckable(True)
        self.openButton.setAutoExclusive(True)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_1)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    border-radius: 4px;\n"
"    border:1px solid #ccc;\n"
"    padding: 1px;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_1, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(AppcheckerWindow)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextEdit{\n"
"    border-radius: 4px;\n"
"    border:1px solid #ccc;\n"
"    padding: 1px;\n"
"}")
        self.textBrowser.setMarkdown("")
        self.textBrowser.setOverwriteMode(False)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.line = QtWidgets.QFrame(AppcheckerWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 2, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(AppcheckerWindow)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayoutBar = QtWidgets.QGridLayout()
        self.gridLayoutBar.setObjectName("gridLayoutBar")
        self.labelHint = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.labelHint.setFont(font)
        self.labelHint.setText("")
        self.labelHint.setObjectName("labelHint")
        self.gridLayoutBar.addWidget(self.labelHint, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.labelMiniSDKVersion = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.labelMiniSDKVersion.setFont(font)
        self.labelMiniSDKVersion.setText("")
        self.labelMiniSDKVersion.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelMiniSDKVersion.setObjectName("labelMiniSDKVersion")
        self.gridLayout_6.addWidget(self.labelMiniSDKVersion, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 2, 1, 1)
        self.labelPackage = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.labelPackage.setFont(font)
        self.labelPackage.setText("")
        self.labelPackage.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelPackage.setObjectName("labelPackage")
        self.gridLayout_6.addWidget(self.labelPackage, 0, 1, 1, 1)
        self.labelVersion = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.labelVersion.setFont(font)
        self.labelVersion.setText("")
        self.labelVersion.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelVersion.setObjectName("labelVersion")
        self.gridLayout_6.addWidget(self.labelVersion, 1, 1, 1, 1)
        self.labelSDKVersion = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.labelSDKVersion.setFont(font)
        self.labelSDKVersion.setText("")
        self.labelSDKVersion.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSDKVersion.setObjectName("labelSDKVersion")
        self.gridLayout_6.addWidget(self.labelSDKVersion, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 2, 1, 1)
        self.gridLayoutBar.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayoutBar, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(AppcheckerWindow)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(250, 120))
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkButton = QtWidgets.QPushButton(self.groupBox_3)
        self.checkButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.checkButton.setFont(font)
        self.checkButton.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.checkButton.setObjectName("checkButton")
        self.gridLayout_3.addWidget(self.checkButton, 1, 0, 1, 1)
        self.fullInfoButton = QtWidgets.QPushButton(self.groupBox_3)
        self.fullInfoButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.fullInfoButton.setFont(font)
        self.fullInfoButton.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.fullInfoButton.setObjectName("fullInfoButton")
        self.gridLayout_3.addWidget(self.fullInfoButton, 1, 1, 1, 1)
        self.horizontalLayoutIcon = QtWidgets.QHBoxLayout()
        self.horizontalLayoutIcon.setObjectName("horizontalLayoutIcon")
        self.labelGoogle = QtWidgets.QLabel(self.groupBox_3)
        self.labelGoogle.setMaximumSize(QtCore.QSize(40, 40))
        self.labelGoogle.setText("")
        self.labelGoogle.setPixmap(QtGui.QPixmap("ui/resources/pictures/google-play.png"))
        self.labelGoogle.setScaledContents(True)
        self.labelGoogle.setOpenExternalLinks(True)
        self.labelGoogle.setObjectName("labelGoogle")
        self.horizontalLayoutIcon.addWidget(self.labelGoogle)
        self.labelApkpure = QtWidgets.QLabel(self.groupBox_3)
        self.labelApkpure.setMaximumSize(QtCore.QSize(40, 40))
        self.labelApkpure.setText("")
        self.labelApkpure.setPixmap(QtGui.QPixmap("ui/resources/pictures/apkpure.png"))
        self.labelApkpure.setScaledContents(True)
        self.labelApkpure.setOpenExternalLinks(True)
        self.labelApkpure.setObjectName("labelApkpure")
        self.horizontalLayoutIcon.addWidget(self.labelApkpure)
        self.labelCombo = QtWidgets.QLabel(self.groupBox_3)
        self.labelCombo.setMaximumSize(QtCore.QSize(40, 40))
        self.labelCombo.setText("")
        self.labelCombo.setPixmap(QtGui.QPixmap("ui/resources/pictures/apkcombo.png"))
        self.labelCombo.setScaledContents(True)
        self.labelCombo.setOpenExternalLinks(True)
        self.labelCombo.setObjectName("labelCombo")
        self.horizontalLayoutIcon.addWidget(self.labelCombo)
        self.gridLayout_3.addLayout(self.horizontalLayoutIcon, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_3, 3, 1, 1, 1)

        self.retranslateUi(AppcheckerWindow)
        QtCore.QMetaObject.connectSlotsByName(AppcheckerWindow)

    def retranslateUi(self, AppcheckerWindow):
        _translate = QtCore.QCoreApplication.translate
        AppcheckerWindow.setWindowTitle(_translate("AppcheckerWindow", "APK Checker"))
        self.openButton.setText(_translate("AppcheckerWindow", "Open APK"))
        self.textEdit.setHtml(_translate("AppcheckerWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'微软雅黑\',\'微软雅黑\'; font-size:9.07563pt;\"><br /></p></body></html>"))
        self.textBrowser.setHtml(_translate("AppcheckerWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.07563pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("AppcheckerWindow", "Package name"))
        self.label_4.setText(_translate("AppcheckerWindow", "Target SDK Version"))
        self.label_2.setText(_translate("AppcheckerWindow", "Version name"))
        self.label_3.setText(_translate("AppcheckerWindow", "Min SDK Version"))
        self.checkButton.setText(_translate("AppcheckerWindow", "Check"))
        self.fullInfoButton.setText(_translate("AppcheckerWindow", "Manifest.xml"))
