# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comment_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommentWindow(object):
    def setupUi(self, CommentWindow):
        CommentWindow.setObjectName("CommentWindow")
        CommentWindow.resize(798, 453)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        CommentWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/pictures/hacker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CommentWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(CommentWindow)
        self.gridLayout.setContentsMargins(20, 0, 20, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(CommentWindow)
        self.textBrowser.setStyleSheet("QTextEdit{\n"
"    border-radius: 4px;\n"
"    border:1px solid #ccc;\n"
"    padding: 1px;\n"
"}")
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(CommentWindow)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    border-radius: 4px;\n"
"    border:1px solid #ccc;\n"
"    padding: 1px;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 1)
        self.rawLabel = QtWidgets.QLabel(CommentWindow)
        self.rawLabel.setObjectName("rawLabel")
        self.gridLayout_2.addWidget(self.rawLabel, 0, 0, 1, 1)
        self.formatLabel = QtWidgets.QLabel(CommentWindow)
        self.formatLabel.setObjectName("formatLabel")
        self.gridLayout_2.addWidget(self.formatLabel, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.transLabel = QtWidgets.QLabel(CommentWindow)
        self.transLabel.setObjectName("transLabel")
        self.horizontalLayout_3.addWidget(self.transLabel)
        spacerItem = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.transComboBox = QtWidgets.QComboBox(CommentWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.transComboBox.setFont(font)
        self.transComboBox.setStyleSheet("QComboBox{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}")
        self.transComboBox.setObjectName("transComboBox")
        self.transComboBox.addItem("")
        self.transComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.transComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.transBrowser = QtWidgets.QTextBrowser(CommentWindow)
        self.transBrowser.setStyleSheet("QTextEdit{\n"
"    border-radius: 4px;\n"
"    border:1px solid #ccc;\n"
"    padding: 1px;\n"
"}")
        self.transBrowser.setOpenExternalLinks(True)
        self.transBrowser.setObjectName("transBrowser")
        self.gridLayout.addWidget(self.transBrowser, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(CommentWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formatButton = QtWidgets.QPushButton(self.groupBox)
        self.formatButton.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.formatButton.setFont(font)
        self.formatButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.formatButton.setStyleSheet("")
        self.formatButton.setCheckable(True)
        self.formatButton.setAutoExclusive(True)
        self.formatButton.setAutoDefault(False)
        self.formatButton.setObjectName("formatButton")
        self.horizontalLayout_2.addWidget(self.formatButton)
        self.transButton = QtWidgets.QPushButton(self.groupBox)
        self.transButton.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.transButton.setFont(font)
        self.transButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.transButton.setStyleSheet("")
        self.transButton.setCheckable(True)
        self.transButton.setAutoExclusive(True)
        self.transButton.setObjectName("transButton")
        self.horizontalLayout_2.addWidget(self.transButton)
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.covertButton = QtWidgets.QPushButton(CommentWindow)
        self.covertButton.setMinimumSize(QtCore.QSize(0, 0))
        self.covertButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.covertButton.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    height: 36px;\n"
"    width: 36px;    \n"
"    \n"
"      border-radius: 18px;\n"
"    /*border:1px solid #dadada;\n"
"    white-space: nowrap;*/\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.covertButton.setCheckable(True)
        self.covertButton.setAutoExclusive(True)
        self.covertButton.setObjectName("covertButton")
        self.horizontalLayout.addWidget(self.covertButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(CommentWindow)
        QtCore.QMetaObject.connectSlotsByName(CommentWindow)

    def retranslateUi(self, CommentWindow):
        _translate = QtCore.QCoreApplication.translate
        CommentWindow.setWindowTitle(_translate("CommentWindow", "Format Comment"))
        self.rawLabel.setText(_translate("CommentWindow", "Raw Comment"))
        self.formatLabel.setText(_translate("CommentWindow", "Format"))
        self.transLabel.setText(_translate("CommentWindow", "Translation"))
        self.transComboBox.setItemText(0, _translate("CommentWindow", "Baidu"))
        self.transComboBox.setItemText(1, _translate("CommentWindow", "Google"))
        self.formatButton.setText(_translate("CommentWindow", "Format"))
        self.transButton.setText(_translate("CommentWindow", "Translation"))
        self.covertButton.setText(_translate("CommentWindow", "<>"))
