# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'format_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormatWindow(object):
    def setupUi(self, FormatWindow):
        FormatWindow.setObjectName("FormatWindow")
        FormatWindow.resize(798, 454)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        FormatWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/pictures/hacker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormatWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(FormatWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formatButton = QtWidgets.QCommandLinkButton(FormatWindow)
        self.formatButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.formatButton.setFont(font)
        self.formatButton.setMouseTracking(False)
        self.formatButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.formatButton.setStyleSheet("border:5px;\n"
"color:#ffffff;\n"
"font-weight: bold;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(95, 159, 219, 255), stop:1 rgba(0, 159, 219, 255));")
        self.formatButton.setCheckable(True)
        self.formatButton.setObjectName("formatButton")
        self.horizontalLayout.addWidget(self.formatButton)
        self.label_2 = QtWidgets.QLabel(FormatWindow)
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui/resources/pictures/xml.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(FormatWindow)
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/resources/pictures/json-file.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(FormatWindow)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(FormatWindow)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(FormatWindow)
        QtCore.QMetaObject.connectSlotsByName(FormatWindow)

    def retranslateUi(self, FormatWindow):
        _translate = QtCore.QCoreApplication.translate
        FormatWindow.setWindowTitle(_translate("FormatWindow", "Format Output"))
        self.formatButton.setText(_translate("FormatWindow", "Format"))
