# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hash_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HashWindow(object):
    def setupUi(self, HashWindow):
        HashWindow.setObjectName("HashWindow")
        HashWindow.resize(490, 319)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/pictures/hacker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HashWindow.setWindowIcon(icon)
        self.openButton = QtWidgets.QPushButton(HashWindow)
        self.openButton.setGeometry(QtCore.QRect(20, 30, 92, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.hashButton = QtWidgets.QPushButton(HashWindow)
        self.hashButton.setGeometry(QtCore.QRect(20, 80, 92, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.hashButton.setFont(font)
        self.hashButton.setObjectName("hashButton")
        self.textEdit = QtWidgets.QTextEdit(HashWindow)
        self.textEdit.setGeometry(QtCore.QRect(130, 30, 331, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(HashWindow)
        self.textBrowser.setGeometry(QtCore.QRect(130, 80, 331, 201))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(HashWindow)
        QtCore.QMetaObject.connectSlotsByName(HashWindow)

    def retranslateUi(self, HashWindow):
        _translate = QtCore.QCoreApplication.translate
        HashWindow.setWindowTitle(_translate("HashWindow", "Hash"))
        self.openButton.setText(_translate("HashWindow", "Open File"))
        self.hashButton.setText(_translate("HashWindow", "Hash"))
