# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hash_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HashWindow(object):
    def setupUi(self, HashWindow):
        HashWindow.setObjectName("HashWindow")
        HashWindow.resize(900, 550)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/pictures/hacker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HashWindow.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(HashWindow)
        self.gridLayout_2.setContentsMargins(20, 0, 20, 0)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(HashWindow)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.openButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 1, 1, 1)
        self.hashButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.hashButton.setFont(font)
        self.hashButton.setStyleSheet("")
        self.hashButton.setObjectName("hashButton")
        self.gridLayout.addWidget(self.hashButton, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(HashWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textBrowser.setFont(font)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 0, 1, 1)

        self.retranslateUi(HashWindow)
        QtCore.QMetaObject.connectSlotsByName(HashWindow)

    def retranslateUi(self, HashWindow):
        _translate = QtCore.QCoreApplication.translate
        HashWindow.setWindowTitle(_translate("HashWindow", "File Hash"))
        self.openButton.setText(_translate("HashWindow", "Open File"))
        self.hashButton.setText(_translate("HashWindow", "Hash"))
