# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pechecker_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PecheckerWindow(object):
    def setupUi(self, PecheckerWindow):
        PecheckerWindow.setObjectName("PecheckerWindow")
        PecheckerWindow.resize(550, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/pictures/hacker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PecheckerWindow.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(PecheckerWindow)
        self.gridLayout_2.setContentsMargins(20, 11, 20, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(PecheckerWindow)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border:0px\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    text-decoration:none;\n"
"    background:#ffffff;\n"
"    /*color: #fff;*/\n"
"    color:#000000;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"    font-weight:light;\n"
"    border-radius:4px;\n"
"    border:1px solid #dadada;\n"
"    white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton::checked,QPushButton::hover{\n"
"    background-image: url(\"ui/resources/pictures/blue_menu.png\");\n"
"    color:#ffffff;\n"
"    font-weight: bold;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.openButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"    border-radius: 4px;\n"
"    border:1px solid #ccc;\n"
"    padding: 1px;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 1, 1, 1)
        self.checkButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.checkButton.setFont(font)
        self.checkButton.setStyleSheet("")
        self.checkButton.setObjectName("checkButton")
        self.gridLayout.addWidget(self.checkButton, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(PecheckerWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextEdit{\n"
"    border-radius: 4px;\n"
"    border:1px solid #ccc;\n"
"    padding: 1px;\n"
"}")
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 0, 1, 1)

        self.retranslateUi(PecheckerWindow)
        QtCore.QMetaObject.connectSlotsByName(PecheckerWindow)

    def retranslateUi(self, PecheckerWindow):
        _translate = QtCore.QCoreApplication.translate
        PecheckerWindow.setWindowTitle(_translate("PecheckerWindow", "PE Checker"))
        self.openButton.setText(_translate("PecheckerWindow", "Open PE"))
        self.checkButton.setText(_translate("PecheckerWindow", "Check"))
